<a href="https://colab.research.google.com/github/pxnhut1652005/KTLT-ECO-CT7/blob/main/B%C3%A0i_m%E1%BA%ABu_1_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NHIỆM VỤ 2**

In [ ]:
import pandas as pd

# Đọc file CSV đã upload
marketing_data = pd.read_csv("marketing_campaign.csv", sep='\t')

# Xem vài dòng đầu tiên
marketing_data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [ ]:
from google.colab import files

# Bước 1: Tải file từ máy tính lên Colab
uploaded = files.upload()

Saving marketing_campaign.csv to marketing_campaign.csv

In [ ]:
marketing_data = marketing_data[['ID','Year_Birth','Education',
                                 'Marital_Status','Income','Kidhome','Teenhome',
                                 'Dt_Customer','Recency','NumStorePurchases','NumWebVisitsMonth']]

marketing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2240 non-null   int64
 1   Year_Birth         2240 non-null   int64
 2   Education          2240 non-null   object
 3   Marital_Status     2240 non-null   object
 4   Income             2216 non-null   float64
 5   Kidhome            2240 non-null   int64
 6   Teenhome           2240 non-null   int64
 7   Dt_Customer        2240 non-null   object
 8   Recency            2240 non-null   int64
 9   NumStorePurchases  2240 non-null   int64
 10  NumWebVisitsMonth  2240 non-null   int64
dtypes: float64(1), int64(7), object(3)
memory usage: 192.6+ KB

In [4]:
marketing_data.head()
# Remove duplicates across the columns in our dataset:
marketing_data_duplicate = marketing_data.drop_duplicates()
# Delete a specified row at index value 1:
marketing_data.drop(labels=[1], axis=0)
# Delete a single column
marketing_data.drop(labels=['Year_Birth'], axis=1)

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
...,...,...,...,...,...,...,...,...,...,...
2235,10870,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

In [6]:
# Thay giá trị trong cột Teenhome
marketing_data['Teenhome_replaced'] = marketing_data['Teenhome'].replace([0,1,2], ['has no teen','has teen','has teen'])

# Điền giá trị NA trong Income bằng 0
marketing_data['Income'] = marketing_data['Income'].fillna(0)

# Chuyển Income từ float sang int
marketing_data['Income_changed'] = marketing_data['Income'].astype(int)

# Kiểm tra kết quả
marketing_data[['Teenhome', 'Teenhome_replaced', 'Income', 'Income_changed']].head()

   Teenhome Teenhome_replaced   Income  Income_changed
0         0       has no teen  58138.0           58138
1         1          has teen  46344.0           46344
2         0       has no teen  71613.0           71613
3         0       has no teen  26646.0           26646
4         0       has no teen  58293.0           58293

In [7]:
# Check for missing values using the isnull and sum methods
marketing_data.isnull().sum()
# Drop missing values using the dropna method
marketing_data_withoutna = marketing_data.dropna(how = 'any')
marketing_data_withoutna.shape

(2240, 13)